# https://docs.gradle.org/current/userguide/github-actions.html
name: test

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout project sources
                uses: actions/checkout@v3

            -   name: Setup OpenJDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'adopt'
                    java-version: '17.0.6'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Execute Gradle (JUnit) tests
                run: ./gradlew test
