# https://docs.gradle.org/current/userguide/github-actions.html
name: Tests

on:
    push:
    pull_request:

jobs:
    build-gradle-project:
        runs-on: [ubuntu-latest, macos-latest]
        steps:
            -   name: Checkout project sources
                uses: actions/checkout@v3

            -   name: Setup OpenJDK 19
                uses: actions/setup-java@v3
                with:
                    distribution: 'adopt'
                    java-version: '19.0.2'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Execute Gradle (JUnit) tests
                run: ./gradlew test
